module.exports = [
  {
    memoryID: 1,
    userID: 1,
    title: "I Went To The Beach",
    description:
      "I went to the beach with some of my friends today. We had a great time there, I am usually pretty anxious about being out especially now with all that is going on in the world, but I was happy to be able to spend some time with my friends today and unwind a bit, it was much needed.",
    dateOfMemory: "2021-06-25 12:00:00",
    feeling: "happy",
    helpfulThought: true,
    relatedMoment: "In My Feelings by Drake",
  },
  {
    memoryID: 2,
    userID: 2,
    title: "Met a new friend",
    description:
      "Today, I got out of my comfort zone and met a new friend. It was great being able to make a new connection with someone I never met before. We have a lot in common.",
    dateOfMemory: "2021-06-27 14:00:00",
    feeling: "ok",
    helpfulThought: true,
    relatedMoment: "",
  },
  {
    memoryID: 3,
    userID: 1,
    title: "I got hired!!!!!!!",
    description:
      "Finally! I had been applying to so many jobs recently and I thought this day would never come, I finally got my dream job as a developer and I can't wait to start :D",
    dateOfMemory: "2021-08-01 16:00:00",
    feeling: "happy",
    helpfulThought: true,
    relatedMoment: "One Right Now by Post Malone",
  },
  {
    memoryID: 4,
    userID: 1,
    title: "Didn't have the best day today",
    description:
      "With everything going in the world, I felt a bit down today. It rained too so that didn't help my mood too much either.",
    dateOfMemory: "2019-06-22 19:37:00",
    feeling: "sad",
    helpfulThought: false,
    relatedMoment: "Save Your Tears by The Weeknd",
  },
  {
    memoryID: 5,
    userID: 3,
    title: "Finished my assignment!",
    description:
      "Took me forever and I procrastinated on it from time to time, but I finally got it done! This assignment is my everything so to have it finally finished is a miracle!",
    dateOfMemory: "2021-10-01 13:00:00",
    feeling: "happy",
    helpfulThought: true,
    relatedMoment: "",
  },
  {
    memoryID: 6,
    userID: 3,
    title: "Ate a piece of cake from my local bakery.",
    description:
      "I went to a bakery close to my house. This bakery has this chocolate cake that I never thought I'd like until I tried it. I'm going back again next week FOR SURE!",
    dateOfMemory: "2021-08-01 12:00:00",
    feeling: "happy",
    helpfulThought: true,
    relatedMoment: "Cake By The Ocean by DNCE",
  },
  {
    memoryID: 7,
    userID: 2,
    title: "Memory 7",
    description: "Description 7",
    dateOfMemory: "2021-11-01 13:13:00",
    feeling: "upset",
    helpfulThought: false,
    relatedMoment: "Downtown Toronto",
  },
  {
    memoryID: 8,
    userID: 3,
    title: "Memory 8",
    description: "Description 8",
    dateOfMemory: "2021-11-12 05:25:04",
    feeling: "ok",
    helpfulThought: true,
    relatedMoment: "Michael Buble's Christmas Album",
  },
  {
    memoryID: 9,
    userID: 2,
    title: "Memory 9",
    description: "Description 9",
    dateOfMemory: "2021-11-20 12:00:00",
    feeling: "happy",
    helpfulThought: true,
    relatedMoment: "One Right Now by The Weeknd",
  },
];
